Update Test CSharpMath.Ios.yml

diff --git a/.github/workflows/Test CSharpMath.Ios.yml b/.github/workflows/Test CSharpMath.Ios.yml
--- a/.github/workflows/Test CSharpMath.Ios.yml
+++ b/.github/workflows/Test CSharpMath.Ios.yml
@@ -10,12 +10,14 @@ jobs:
         submodules: 'recursive'
     - run: nuget restore CSharpMath.sln
     - run: msbuild CSharpMath.Ios.Tests
-    - name: Run a heavily modified version of https://gist.github.com/jerrymarino/1f9eb6a06c423f9744ea297d80193a9b
+    - name: Run tests
       env:
         IOS_SIM_NAME: iPhone 11 # https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#installed-simulators
         BUNDLE_IDENTIFIER: CSharpMath.Ios.Unit-Tests # Located inside CSharpMath.Ios.Tests Info.plist file
         APP_PATH: CSharpMath.Ios.Tests/bin/iPhoneSimulator/Debug/CSharpMath.Ios.Tests.app
       run: |
+        # This script is a heavily modified version of https://gist.github.com/jerrymarino/1f9eb6a06c423f9744ea297d80193a9b
+        
         IOS_SIM_UDID=`xcrun simctl list | grep -w '$IOS_SIM_NAME' | awk 'match($0, /\(([-0-9A-F]+)\)/) { print substr( $0, RSTART + 1, RLENGTH - 2 )}' | head -1`
         SIMULATOR_PATH='/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/Contents/MacOS/Simulator'
         
@@ -72,5 +74,11 @@ jobs:
         # Launch the app program into the booted sim
         # - Pipe the output to a log file
         # - Run in the background
-        xcrun simctl launch --console booted $BUNDLE_IDENTIFIER 2>&1
+        TESTS_OUTPUT=`xcrun simctl launch --console booted $BUNDLE_IDENTIFIER 2>&1`
         # 2>&1 means "redirect stderr to stdout": https://stackoverflow.com/a/818284/5429648
+
+        echo '$TESTS_OUTPUT'
+
+        if [[ '$TESTS_OUTPUT' == *"[FAIL]"* ]]
+        then exit 1 # Fail this workflow
+        fi
