Exit last

diff --git a/.github/workflows/Test all projects.yml b/.github/workflows/Test all projects.yml
--- a/.github/workflows/Test all projects.yml
+++ b/.github/workflows/Test all projects.yml
@@ -126,15 +126,15 @@ jobs:
         # 2>&1 means "redirect stderr to stdout": https://stackoverflow.com/a/818284/5429648
 
         echo "$TESTS_OUTPUT"
-
-        if [[ "$TESTS_OUTPUT" == *"[FAIL]"* ]]
-        then exit 1 # Fail this workflow
-        fi
         
         # Move artifacts (generated pictures) to a known path for uploading
         TESTS_ARTIFACTS="`xcrun simctl get_app_container booted $BUNDLE_IDENTIFIER data`/Documents/*"
         mkdir -p /tmp/tests_artifacts
-        mv $TESTS_ARTIFACTS /tmp/tests_artifacts
+        mv "$TESTS_ARTIFACTS" /tmp/tests_artifacts
+
+        if [[ "$TESTS_OUTPUT" == *"[FAIL]"* ]]
+        then exit 1 # Fail this workflow
+        fi
     - uses: actions/upload-artifact@v2
       if: always() # Run even when a previous step failed: https://stackoverflow.com/a/58859404/5429648
       with:
